15_1_balloon
TheIronHobo/InterviewPrep pull request #42
Opened 2024-06-20 01:15 UTC by AaronDabney

## Balloon 🎈
- Added `balloonHandler` function
- `balloonHandler` is added to first element with "balloon"` ID
- Balloon is centered via style tag to any browser dimension
- `balloonHandler` event listener is removed from window by `explosion` function

https://github.com/AaronDabney/InterviewPrep/assets/172078271/2a23face-c6c0-49d8-80b5-a56f5ed9e9d7

2024-07-04 04:14 UTC, CalHinshaw requested changes
This is a great start!

2024-07-04 04:14 UTC, CalHinshaw commented on eloquentjs/15_1_balloon/index.html
> +        }
a line break is standard

2024-07-04 04:14 UTC, CalHinshaw commented on eloquentjs/15_1_balloon/index.js
> +        timeout = setTimeout(() =>{
I don't think you should use setTimeout here. It would be better to avoid that complexity.

2024-07-05 03:09 UTC, AaronDabney commented
https://github.com/AaronDabney/InterviewPrep/assets/172078271/7d72c98f-eb95-414a-9551-8e000cd5dfa1

2024-07-05 04:20 UTC, CalHinshaw approved these changes
This looks a lot simpler, nice work.

2024-07-05 05:01 UTC, merged